name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build Extension
        run: pnpm pack:zip

      - name: Upload assets to a Release
        uses: meeDamian/github-release@v2.0.3
        with:
          files: extension.zip
          token: ${{ secrets.RELEASE_TOKEN }}
          allow_override: true
          gzip: false
